apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
stringData:
  # Replace these values with actual secrets from your secret management system
  # DO NOT commit actual secrets to version control
  CONNECTION_STRING: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
  JWT_KEY: "${JWT_SECRET_KEY}"  # Must be at least 256 bits (32 characters) for HS256
  JWT_ISSUER: "${JWT_ISSUER}"
  JWT_AUDIENCE: "${JWT_AUDIENCE}"
  JWT_DURATION: "${JWT_DURATION_MINUTES}"

---
# Example of using external secret operator (recommended for production)
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: vault-backend
# spec:
#   provider:
#     vault:
#       server: "https://vault.example.com"
#       path: "secret"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "auth-service"

---
# Example External Secret
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: auth-service-secrets
# spec:
#   refreshInterval: 10s
#   secretStoreRef:
#     name: vault-backend
#     kind: SecretStore
#   target:
#     name: auth-service-secrets
#     creationPolicy: Owner
#   data:
#   - secretKey: CONNECTION_STRING
#     remoteRef:
#       key: auth-service
#       property: connection_string
#   - secretKey: JWT_KEY
#     remoteRef:
#       key: auth-service
#       property: jwt_key 