apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
stringData:
  CONNECTION_STRING: "Host=postgres-service.databasens.svc.cluster.local;Port=5432;Database=SurveyDb;Username=postgres;Password=#roVin123"
  JWT_KEY: "ThisIsASecretKeyWithAtLeast128Bits"
  JWT_ISSUER: "AuthService"
  JWT_AUDIENCE: "SurveyApp"
  JWT_DURATION: "60"